### ISSUE TITLE
"Profile bleed" with AP randomizer?

### ISSUE THREAD

**Issue by dgarroDC** [dgarroDC/CustomShipLogModes#4]
Bug detected in Ixrec/OuterWildsArchipelagoRandomizer, possibly caused by CSLM?

Reported by @Ixrec
<img width="934" alt="image" src="https://github.com/user-attachments/assets/61bff1a1-a406-473b-8b89-5109b34dc8e9">

**Comment by Ixrec** [comment]
feel free to close this, turned out it had nothing to do with CSLM

![image](https://github.com/user-attachments/assets/684fb663-45e2-4744-a243-88856ca74b37)
